### ISSUE TITLE
missing headers

### ISSUE THREAD

**Issue by The-Phoenics** [k4saad/Hotel_Management_System#3]
Hey, I was adding `cmake` build script for this project but there is not such header files named 
```
#include <sha.h>
#include <hex.h>
```
which are included in `Admin.cpp`

**Comment by k4saad** [comment]
hii, I used Crypto++, but I haven't pushed it on github. Should I push it?

**Comment by kar03an** [comment]
Hi @k4saad, it would be great if all of the source code is available, in order to compile the project.

**Comment by k4saad** [comment]
Hii, @Karansemwal I added the required files, you can ask me anytime if required.
